"""empty message

Revision ID: 08547e9fe766
Revises: 916595672be4
Create Date: 2023-10-07 12:17:48.866519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08547e9fe766'
down_revision = '916595672be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
